language: node_js
node_js:
  - "0.11"
before_install:
  - npm install -g npm@2.1.7
  - npm i -g
  - npm i -g jasmine-node
script:
  - jasmine-node --version
  - pwd && ls
  - jasmine-node --verbose --test-dir /home/travis/build/angularity/node-angularity/test
