language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
      - node_js: "0.11"
      - node_js: "0.8"
  fast_finish: true
before_install:
  - npm install -g npm@2.1.7
  - npm install -g
  - node -v
  - npm -v
script:
  - pwd && ls
  - node node_modules/jasmine-node/bin/jasmine-node --version
  - npm run test
