language: node_js

node_js:
  - "0.10"

matrix:
  fast_finish: true

before_install:
  - npm install -g npm@2.1.7
  - node -v
  - npm -v
  - npm install -g

script:
  - pwd
  - ls
  - node node_modules/jasmine-node/bin/jasmine-node --version
  - npm test
