language: node_js

sudo: false

node_js:
  - "0.10"

matrix:
  fast_finish: true

install:
  - npm install -g npm@2.1.7
  - node -v
  - npm -v          # expect npm 2.x
  - npm install -g  # global install is neccessary to run the cli as intended
  - npm link        # make the globally installed modules available locally instead of installing from scratch
  - pwd
  - ls

script:
  - node node_modules/jasmine-node/bin/jasmine-node --version # expect jasmine 2.x
  - npm run lint
  - npm test

after_success:
  - npm run autodocs
env:
  global:
  - secure: U+IdWhk/tUsG9e7hOxxeGhzbJ3iYYtvRyz4zExVI6JJz22TJX5UXwJJQmrrNcM1bwt1GTAbX3xYavE+kqs9I5wyeMX92+/o1gz2vp/46wRXAKC/X8lULVH0vopVtnKZnyKUIzQTYd7NxX0JsweJ9Y/4szkskygnTDu6lXkpPPVk=
  # - DOCUMENT_BRANCH: ${TRAVIS_BRANCH}
  - FLAG_PUBLISH_ON_RELEASE: 'true'
  - REPO_SLUG: 'angularity/angularity.github.io'
  - GH_PUBLISH_BRANCH: 'master'
