language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
      - node_js: "0.11"
      - node_js: "0.8"
  fast_finish: true
before_install:
  - npm install -g npm@2.1.7
  - npm i -g
  - npm i -g jasmine-node
  - node -v
  - npm -v
  - jasmine-node --version
script:
  - pwd && ls
  - jasmine-node --verbose --test-dir /home/travis/build/angularity/node-angularity/test/specs