environment:
  matrix:
    - nodejs_version: "0.10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2.1.7
  - set PATH=%APPDATA%\npm;%PATH%
  - node -v
  - npm -v
  - npm install -g

test_script:
  - echo %cd%
  - dir /w
  - npm test

build: off