environment:
  matrix:
    - nodejs_version: "0.11"
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "0.11"
    - nodejs_version: "0.8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i -g
  - npm i -g jasmine-node
  - node -v
  - npm -v
  - jasmine-node --version

test_script:
  - npm test

build: off