environment:
  matrix:
    - nodejs_version: "0.10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - node -v
  - npm -v
  - npm i -g
  - npm link
  - angularity -v
  - npm test

build: off