environment:
  matrix:
    - nodejs_version: "0.10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i -g
  - npm i -g jasmine-node
  - node -v
  - npm -v
  - jasmine-node --version

test_script:
  - jasmine-node --verbose --test-dir C:\projects\node-angularity\test\specs

build: off